import { updateStatus } from "../api/assessment";
import Modal from "../components/ui-reusable/Modal";
import { RatingInput } from "../components/ui-reusable/RatingInput";
import { AuthContext } from "../Provider/AuthProvider";

import { useContext, useEffect, useState } from "react";
const RatingModal = ({
  isOpen,
  onClose,
  onSubmit,
  selectedId,
  maxStars = 5,
  initialRating = 0,
  title = "Share Your Feedback",
}) => {
  const [rating, setRating] = useState(initialRating);
  const [comment, setComment] = useState("");
  const { userData } = useContext(AuthContext) || {};

  useEffect(() => {
    if (isOpen) setRating(initialRating);
  }, [isOpen, initialRating]);

  if (!isOpen) return null;

  const handleSubmit = async (e) => {
    e.preventDefault();

    const obj = {
      ratings: rating,
      clinicianId: userData?.id,
    };
    //console.log(obj);
    const result = await updateStatus(selectedId, obj);
    //console.log("Updated submission:", result);
    onSubmit?.({ rating, comment });
  };

  return (
    <Modal
      classname="w-[30vw] h-auto"
      isOpen={isOpen}
      closeModal={onClose}
      title={title}
    >
      <p className="text-xs text-[#3C3C4399] -mt-7">
        The summary is generated by AI based on the patient's assessment. There
        might be some inconsistency. Your review can help us make it better in
        future.
      </p>

      <div className="mt-5 flex flex-col items-center gap-2">
        <RatingInput value={rating} onChange={setRating} max={maxStars} />
        <p className="text-sm text-gray-600">
          How would you rate the clarity and accuracy of this summary?
        </p>
      </div>

      {/* <form onSubmit={handleSubmit} className="mt-6">
        <label className="text-sm text-gray-700 text-center items-center">
          Write down your thoughts (optional)
        </label>
        <textarea
          value={comment}
          onChange={(e) => setComment(e.target.value)}
          className="mt-2 w-full h-28 rounded-xl border placeholder:text-sm border-gray-300 p-3 outline-none"
          placeholder="Type here..."
        />

        <button
          type="submit"
          className="mt-4 w-full rounded-full cursor-pointer bg-[#0A4863] text-white py-2 font-medium hover:opacity-95 active:opacity-90"
        >
          Submit this review
        </button>
      </form> */}
    </Modal>
  );
};

export default RatingModal;
